# Generated by Django 5.2.1 on 2025-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insumos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insumo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="insumos/"),
        ),
    ]
