# Generated by Django 5.2.1 on 2025-07-25 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre Categoría Insumo",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="categorias_insumos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Insumo",
                "verbose_name_plural": "Categorías de Insumos",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("direccion", models.TextField(blank=True)),
                ("telefono", models.CharField(blank=True, max_length=25)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponenteProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_necesaria", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Componente de Producto (BOM)",
                "verbose_name_plural": "Componentes de Productos (BOM)",
            },
        ),
        migrations.CreateModel(
            name="EstadoOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("contacto", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=25)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=50, unique=True)),
                (
                    "fecha_emision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "total_facturado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialOV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_evento", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "tipo_evento",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'Estado Cambiado', 'Producción Iniciada', 'Facturado'",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Orden de Venta",
                "verbose_name_plural": "Historiales de Órdenes de Venta",
                "ordering": ["-fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="insumos/"),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "cantidad_en_pedido",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Cantidad en Pedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemOrdenVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario_venta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Unit. en Venta",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfertaProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_unitario_compra",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio de Compra Unitario",
                    ),
                ),
                (
                    "tiempo_entrega_estimado_dias",
                    models.IntegerField(
                        default=0, verbose_name="Tiempo de Entrega Estimado (días)"
                    ),
                ),
                (
                    "fecha_actualizacion_precio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Última Actualización del Precio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta de Proveedor por Insumo",
                "verbose_name_plural": "Ofertas de Proveedores por Insumos",
                "ordering": ["insumo__descripcion", "proveedor__nombre"],
            },
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_orden",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° Orden de Compra"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("compra", "Orden de Compra")],
                        default="compra",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("APROBADA", "Aprobada"),
                            ("ENVIADA_PROVEEDOR", "Enviada al Proveedor"),
                            ("CONFIRMADA_PROVEEDOR", "Confirmada por Proveedor"),
                            ("EN_TRANSITO", "En Tránsito"),
                            ("RECIBIDA_PARCIAL", "Recibida Parcialmente"),
                            ("RECIBIDA_TOTAL", "Recibida Totalmente"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=30,
                    ),
                ),
                (
                    "cantidad_principal",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad Insumo Principal"
                    ),
                ),
                (
                    "precio_unitario_compra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Unit. Compra (de la oferta)",
                    ),
                ),
                (
                    "total_orden_compra",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("fecha_estimada_entrega", models.DateField(blank=True, null=True)),
                (
                    "numero_tracking",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notas", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_op",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="N° Orden de Producción",
                    ),
                ),
                ("cantidad_a_producir", models.PositiveIntegerField()),
                (
                    "fecha_solicitud",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_inicio_real", models.DateTimeField(blank=True, null=True)),
                ("fecha_inicio_planificada", models.DateField(blank=True, null=True)),
                ("fecha_fin_real", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin_planificada", models.DateField(blank=True, null=True)),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ov",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° Orden de Venta"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente Confirmación"),
                            ("CONFIRMADA", "Confirmada (Esperando Producción)"),
                            ("INSUMOS_SOLICITADOS", "Insumos Solicitados"),
                            ("PRODUCCION_INICIADA", "Producción Iniciada"),
                            ("PRODUCCION_CON_PROBLEMAS", "Producción con Problemas"),
                            ("LISTA_ENTREGA", "Lista para Entrega"),
                            ("COMPLETADA", "Completada/Entregada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=50,
                    ),
                ),
                (
                    "total_ov",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total OV",
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PasswordChangeRequired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("contacto", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=25)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reportes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_reporte", models.CharField(max_length=20, unique=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("tipo_problema", models.CharField(max_length=100)),
                ("informe_reporte", models.TextField(blank=True, null=True)),
                (
                    "resuelto",
                    models.BooleanField(
                        default=False, verbose_name="¿Problema Resuelto?"
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Resolución"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolDescripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción del rol"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectorAsignado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditoriaAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=255)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
