# Generated by Django 5.2.1 on 2025-07-26 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("App_LUMINOVA", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("insumos", "0001_initial"),
        ("productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="componenteproducto",
            name="producto_terminado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="componentes_requeridos",
                to="productos.productoterminado",
            ),
        ),
        migrations.AddField(
            model_name="historialov",
            name="realizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemordenventa",
            name="producto_terminado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="productos.productoterminado",
            ),
        ),
        migrations.AddField(
            model_name="orden",
            name="insumo_principal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="insumos.insumo",
                verbose_name="Insumo Principal",
            ),
        ),
        migrations.AddField(
            model_name="orden",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_de_compra_a_proveedor",
                to="insumos.proveedor",
            ),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="estado_op",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ops_estado",
                to="App_LUMINOVA.estadoorden",
            ),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="producto_a_producir",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_produccion",
                to="productos.productoterminado",
            ),
        ),
        migrations.AddField(
            model_name="ordenventa",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_venta",
                to="App_LUMINOVA.cliente",
            ),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="orden_venta_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ops_generadas",
                to="App_LUMINOVA.ordenventa",
            ),
        ),
        migrations.AddField(
            model_name="itemordenventa",
            name="orden_venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_ov",
                to="App_LUMINOVA.ordenventa",
            ),
        ),
        migrations.AddField(
            model_name="historialov",
            name="orden_venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="App_LUMINOVA.ordenventa",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="orden_venta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factura_asociada",
                to="App_LUMINOVA.ordenventa",
            ),
        ),
        migrations.AddField(
            model_name="passwordchangerequired",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_change_required",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportes",
            name="orden_produccion_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_incidencia",
                to="App_LUMINOVA.ordenproduccion",
            ),
        ),
        migrations.AddField(
            model_name="reportes",
            name="reportado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roldescripcion",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descripcion_extendida",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="reportes",
            name="sector_reporta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_originados_aqui",
                to="App_LUMINOVA.sectorasignado",
            ),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="sector_asignado_op",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ops_sector",
                to="App_LUMINOVA.sectorasignado",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="componenteproducto",
            unique_together={("producto_terminado", "insumo")},
        ),
    ]
