# Generated by Django 5.2.1 on 2025-07-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordenproduccion",
            name="estado_op",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="insumo_principal",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="proveedor",
        ),
        migrations.RemoveField(
            model_name="ordenproduccion",
            name="orden_venta_origen",
        ),
        migrations.RemoveField(
            model_name="ordenproduccion",
            name="producto_a_producir",
        ),
        migrations.RemoveField(
            model_name="ordenproduccion",
            name="sector_asignado_op",
        ),
        migrations.RemoveField(
            model_name="reportes",
            name="orden_produccion_asociada",
        ),
        migrations.RemoveField(
            model_name="reportes",
            name="reportado_por",
        ),
        migrations.RemoveField(
            model_name="reportes",
            name="sector_reporta",
        ),
        migrations.DeleteModel(
            name="ComponenteProducto",
        ),
        migrations.DeleteModel(
            name="EstadoOrden",
        ),
        migrations.DeleteModel(
            name="Orden",
        ),
    ]
