# Generated by Django 5.2.1 on 2025-07-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0003_remove_ordenproduccion_estado_op_and_more"),
        ("productos", "0002_estadoorden_sectorasignado_ordenproduccion_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrdenProduccion",
        ),
        migrations.DeleteModel(
            name="Reportes",
        ),
        migrations.DeleteModel(
            name="SectorAsignado",
        ),
    ]
