# Generated by Django 5.2.1 on 2025-05-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0007_remove_insumo_precio_unitario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insumo",
            name="cantidad_en_pedido",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cantidad en Pedido a Proveedores"
            ),
        ),
    ]
