# Generated by Django 5.2.1 on 2025-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0012_alter_insumo_fabricante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insumo",
            name="cantidad_en_pedido",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Cantidad en Pedido"
            ),
        ),
        migrations.AlterField(
            model_name="orden",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("APROBADA", "Aprobada"),
                    ("ENVIADA_PROVEEDOR", "Enviada al Proveedor"),
                    ("CONFIRMADA_PROVEEDOR", "Confirmada por Proveedor"),
                    ("EN_TRANSITO", "En Tránsito"),
                    ("RECIBIDA_PARCIAL", "Recibida Parcialmente"),
                    ("RECIBIDA_TOTAL", "Recibida Totalmente"),
                    ("COMPLETADA", "Completada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="BORRADOR",
                max_length=30,
            ),
        ),
    ]
