# Generated by Django 5.2.1 on 2025-06-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0013_alter_insumo_cantidad_en_pedido_alter_orden_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoterminado",
            name="op_asociada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos_terminados",
                to="App_LUMINOVA.ordenproduccion",
            ),
        ),
    ]
