# Generated by Django 5.2.1 on 2025-07-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0018_passwordchangerequired"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("ubicacion", models.CharField(blank=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="insumo",
            name="deposito",
            field=models.ForeignKey(
                blank=True,
                help_text="Depósito al que pertenece este insumo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insumos",
                to="App_LUMINOVA.deposito",
            ),
        ),
        migrations.AddField(
            model_name="loteproductoterminado",
            name="deposito",
            field=models.ForeignKey(
                blank=True,
                help_text="Depósito donde se encuentra el lote",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_productos_terminados",
                to="App_LUMINOVA.deposito",
            ),
        ),
        migrations.AddField(
            model_name="productoterminado",
            name="deposito",
            field=models.ForeignKey(
                blank=True,
                help_text="Depósito al que pertenece este producto terminado",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos_terminados",
                to="App_LUMINOVA.deposito",
            ),
        ),
    ]
