# Generated by Django 5.2.1 on 2025-07-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0018_passwordchangerequired"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("ubicacion", models.CharField(blank=True, max_length=255, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Depósito",
                "verbose_name_plural": "Depósitos",
            },
        ),
        migrations.RemoveField(
            model_name="productoterminado",
            name="stock",
        ),
        migrations.CreateModel(
            name="StockProductoTerminado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0)),
                (
                    "deposito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks_productos",
                        to="App_LUMINOVA.deposito",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="App_LUMINOVA.productoterminado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock de Producto Terminado por Depósito",
                "verbose_name_plural": "Stocks de Productos Terminados por Depósito",
                "unique_together": {("producto", "deposito")},
            },
        ),
    ]
