# Generated by Django 5.2.1 on 2025-07-29 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0019_deposito_insumo_deposito_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriainsumo",
            name="deposito",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_insumo",
                to="App_LUMINOVA.deposito",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categoriaproductoterminado",
            name="deposito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_producto_terminado",
                to="App_LUMINOVA.deposito",
            ),
        ),
    ]
