# Generated by Django 5.2.1 on 2025-07-30 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0020_categoriainsumo_deposito_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriainsumo",
            name="deposito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_insumo",
                to="App_LUMINOVA.deposito",
            ),
        ),
    ]
