# Generated by Django 5.2.1 on 2025-07-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0021_alter_categoriainsumo_deposito"),
        (
            "App_LUMINOVA",
            "0021_alter_categoriainsumo_deposito_movimientostock_and_more",
        ),
    ]

    operations = []
