# Generated by Django 5.2.1 on 2025-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0022_merge_20250731_0829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriainsumo",
            name="nombre",
            field=models.CharField(
                max_length=100, verbose_name="Nombre Categoría Insumo"
            ),
        ),
        migrations.AlterField(
            model_name="categoriaproductoterminado",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre Categoría PT"),
        ),
        migrations.AlterUniqueTogether(
            name="categoriainsumo",
            unique_together={("nombre", "deposito")},
        ),
        migrations.AlterUniqueTogether(
            name="categoriaproductoterminado",
            unique_together={("nombre", "deposito")},
        ),
    ]
