# Generated by Django 5.2.1 on 2025-08-01 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0023_alter_categoriainsumo_nombre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioDeposito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puede_transferir",
                    models.BooleanField(
                        default=True,
                        help_text="Puede realizar transferencias desde/hacia este depósito",
                    ),
                ),
                (
                    "puede_entradas",
                    models.BooleanField(
                        default=True, help_text="Puede registrar entradas de stock"
                    ),
                ),
                (
                    "puede_salidas",
                    models.BooleanField(
                        default=True, help_text="Puede registrar salidas de stock"
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "deposito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios_asignados",
                        to="App_LUMINOVA.deposito",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depositos_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Usuario-Depósito",
                "verbose_name_plural": "Asignaciones Usuario-Depósito",
                "unique_together": {("usuario", "deposito")},
            },
        ),
    ]
