# Generated by Django 5.2.1 on 2025-08-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0010_orden_deposito"),
        ("App_LUMINOVA", "0024_usuariodeposito"),
    ]

    operations = []
