# Generated by Django 5.2.1 on 2025-08-01 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0025_merge_0010_orden_deposito_0024_usuariodeposito"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("stock_bajo", "Stock Bajo"),
                            ("oc_creada", "Orden de Compra Creada"),
                            ("oc_enviada", "Orden de Compra Enviada"),
                            ("oc_recibida", "Orden de Compra Recibida"),
                            ("pedido_recibido", "Pedido Recibido en Depósito"),
                            ("transferencia_solicitada", "Transferencia Solicitada"),
                            ("produccion_completada", "Producción Completada"),
                            ("solicitud_insumos", "Solicitud de Insumos"),
                            ("general", "Notificación General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                (
                    "destinatario_grupo",
                    models.CharField(
                        choices=[
                            ("compras", "Departamento de Compras"),
                            ("ventas", "Departamento de Ventas"),
                            ("deposito", "Depósito"),
                            ("produccion", "Producción"),
                            ("control_calidad", "Control de Calidad"),
                            ("administrador", "Administración"),
                            ("todos", "Todos los usuarios"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "datos_contexto",
                    models.JSONField(
                        blank=True,
                        help_text="Datos adicionales en formato JSON",
                        null=True,
                    ),
                ),
                ("leida", models.BooleanField(default=False)),
                (
                    "atendida",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se tomó acción sobre la notificación",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación del Sistema",
                "verbose_name_plural": "Notificaciones del Sistema",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["destinatario_grupo", "leida"],
                        name="App_LUMINOV_destina_007615_idx",
                    ),
                    models.Index(
                        fields=["tipo", "fecha_creacion"],
                        name="App_LUMINOV_tipo_6c0bf9_idx",
                    ),
                    models.Index(
                        fields=["prioridad", "fecha_creacion"],
                        name="App_LUMINOV_priorid_19dc65_idx",
                    ),
                ],
            },
        ),
    ]
