# Generated by Django 5.2.1 on 2025-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0026_notificacion_sistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="insumo",
            name="notificado_a_compras",
            field=models.BooleanField(
                default=False, help_text="¿Ya fue notificado a compras por stock bajo?"
            ),
        ),
    ]
