# Generated by Django 5.2.1 on 2025-08-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0027_insumo_notificado_a_compras"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="tipo_orden",
            field=models.CharField(
                choices=[
                    ("MTO", "Make to Order (Bajo Demanda)"),
                    ("MTS", "Make to Stock (Para Stock)"),
                ],
                default="MTO",
                help_text="MTO: Producción bajo demanda vinculada a una OV, MTS: Producción para stock",
                max_length=3,
                verbose_name="Tipo de Orden",
            ),
        ),
        migrations.AddField(
            model_name="productoterminado",
            name="produccion_habilitada",
            field=models.BooleanField(
                default=True,
                help_text="Indica si este producto puede ser producido para stock",
                verbose_name="Habilitado para Producción",
            ),
        ),
        migrations.AddField(
            model_name="productoterminado",
            name="stock_minimo",
            field=models.IntegerField(
                default=0,
                help_text="Nivel mínimo de stock que debe mantenerse (punto de reorden)",
                verbose_name="Stock Mínimo",
            ),
        ),
        migrations.AddField(
            model_name="productoterminado",
            name="stock_objetivo",
            field=models.IntegerField(
                default=0,
                help_text="Nivel deseado de stock después de reabastecer",
                verbose_name="Stock Objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="orden_venta_origen",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo para órdenes MTO (Make to Order)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ops_generadas",
                to="App_LUMINOVA.ordenventa",
            ),
        ),
    ]
