# Generated by Django 5.2.1 on 2025-10-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0028_ordenproduccion_tipo_orden_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("razon_social", models.CharField(blank=True, max_length=255)),
                ("cuit", models.CharField(blank=True, max_length=20)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AlterField(
            model_name="deposito",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="deposito",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depositos",
                to="App_LUMINOVA.empresa",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deposito",
            unique_together={("nombre", "empresa")},
        ),
    ]
