# Generated by Django 5.2.1 on 2025-10-02 13:37

from django.db import migrations, models


def set_empresa_default(apps, schema_editor):
    Deposito = apps.get_model('App_LUMINOVA', 'Deposito')
    Empresa = apps.get_model('App_LUMINOVA', 'Empresa')
    empresa, _ = Empresa.objects.get_or_create(nombre="Empresa Default")
    for deposito in Deposito.objects.filter(empresa__isnull=True):
        deposito.empresa = empresa
        deposito.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "App_LUMINOVA",
            "0029_empresa_alter_deposito_nombre_deposito_empresa_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(set_empresa_default),
        migrations.AlterField(
            model_name="deposito",
            name="empresa",
            field=models.ForeignKey(
                to="App_LUMINOVA.Empresa",
                on_delete=models.CASCADE,
                related_name="depositos",
                null=False,
                blank=False,
            ),
        ),
    ]
