# Generated by Django 5.2.1 on 2025-11-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0032_categoriainsumo_empresa_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción del rol"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_empresa",
                        to="App_LUMINOVA.empresa",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_empresa",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol de Empresa",
                "verbose_name_plural": "Roles de Empresa",
                "unique_together": {("empresa", "group")},
            },
        ),
    ]
