# Generated by Django 5.2.1 on 2025-11-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0033_rolempresa"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rolempresa",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="rolempresa",
            name="nombre",
            field=models.CharField(
                default="",
                help_text="Nombre lógico del rol visible en la UI",
                max_length=150,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolempresa",
            unique_together={("empresa", "nombre")},
        ),
    ]
