# Generated by Django 5.2.1 - Migración para completar multi-tenancy
# Esta migración agrega el campo empresa a modelos faltantes y normaliza la base de datos

import django.db.models.deletion
from django.db import migrations, models


def assign_empresa_to_usuariodeposito(apps, schema_editor):
    """
    Asigna la empresa a cada UsuarioDeposito basándose en el depósito relacionado.
    """
    UsuarioDeposito = apps.get_model('App_LUMINOVA', 'UsuarioDeposito')
    
    for ud in UsuarioDeposito.objects.select_related('deposito', 'deposito__empresa').all():
        if ud.deposito and ud.deposito.empresa:
            ud.empresa = ud.deposito.empresa
            ud.save(update_fields=['empresa'])
            print(f"✓ UsuarioDeposito {ud.usuario_id} -> Empresa {ud.empresa.nombre}")


def assign_empresa_to_estadoorden(apps, schema_editor):
    """
    EstadoOrden es un catálogo compartido, pero lo vinculamos a empresas para permitir
    estados personalizados por empresa.
    Asigna la empresa por defecto a todos los estados existentes.
    """
    EstadoOrden = apps.get_model('App_LUMINOVA', 'EstadoOrden')
    Empresa = apps.get_model('App_LUMINOVA', 'Empresa')
    
    # Obtener empresa por defecto (la primera activa)
    empresa_default = Empresa.objects.filter(activa=True).first()
    
    if empresa_default:
        count = EstadoOrden.objects.filter(empresa__isnull=True).update(empresa=empresa_default)
        if count:
            print(f"✓ EstadoOrden: {count} registros asignados a {empresa_default.nombre}")


def assign_empresa_to_sectorasignado(apps, schema_editor):
    """
    SectorAsignado es un catálogo de sectores de producción.
    Asigna la empresa por defecto.
    """
    SectorAsignado = apps.get_model('App_LUMINOVA', 'SectorAsignado')
    Empresa = apps.get_model('App_LUMINOVA', 'Empresa')
    
    empresa_default = Empresa.objects.filter(activa=True).first()
    
    if empresa_default:
        count = SectorAsignado.objects.filter(empresa__isnull=True).update(empresa=empresa_default)
        if count:
            print(f"✓ SectorAsignado: {count} registros asignados a {empresa_default.nombre}")


def assign_empresa_to_auditoriaacceso(apps, schema_editor):
    """
    AuditoriaAcceso registra accesos de usuarios.
    Intentamos asignar empresa basándonos en el perfil del usuario.
    """
    AuditoriaAcceso = apps.get_model('App_LUMINOVA', 'AuditoriaAcceso')
    PerfilUsuario = apps.get_model('App_LUMINOVA', 'PerfilUsuario')
    Empresa = apps.get_model('App_LUMINOVA', 'Empresa')
    
    empresa_default = Empresa.objects.filter(activa=True).first()
    
    if not empresa_default:
        print("⚠ No hay empresa por defecto para AuditoriaAcceso")
        return
    
    for audit in AuditoriaAcceso.objects.filter(empresa__isnull=True).select_related('usuario'):
        if audit.usuario:
            try:
                perfil = PerfilUsuario.objects.get(user=audit.usuario)
                audit.empresa = perfil.empresa
            except PerfilUsuario.DoesNotExist:
                audit.empresa = empresa_default
        else:
            audit.empresa = empresa_default
        audit.save(update_fields=['empresa'])
    
    print(f"✓ AuditoriaAcceso: registros asignados")


def reverse_noop(apps, schema_editor):
    """No hacer nada al revertir - los datos se mantienen"""
    pass


class Migration(migrations.Migration):
    """
    Migración para completar la implementación de multi-tenancy.
    
    MODELOS MULTI-TENANT (con campo empresa):
    - Deposito ✓ (ya tiene)
    - CategoriaInsumo ✓ (ya tiene)
    - CategoriaProductoTerminado ✓ (ya tiene)
    - Insumo ✓ (ya tiene)
    - ProductoTerminado ✓ (ya tiene)
    - Cliente ✓ (ya tiene)
    - Proveedor ✓ (ya tiene)
    - Fabricante ✓ (ya tiene)
    - OrdenVenta ✓ (ya tiene)
    - OrdenProduccion ✓ (ya tiene)
    - Orden ✓ (ya tiene)
    - StockInsumo ✓ (ya tiene)
    - StockProductoTerminado ✓ (ya tiene)
    - MovimientoStock ✓ (ya tiene)
    - NotificacionSistema ✓ (ya tiene)
    - ItemOrdenVenta ✓ (ya tiene)
    - Factura ✓ (ya tiene)
    - OfertaProveedor ✓ (ya tiene)
    - ComponenteProducto ✓ (ya tiene)
    - LoteProductoTerminado ✓ (ya tiene)
    - HistorialOV ✓ (ya tiene)
    - Reportes ✓ (ya tiene)
    - UsuarioDeposito (se agrega en esta migración)
    - EstadoOrden (se agrega en esta migración - catálogo por empresa)
    - SectorAsignado (se agrega en esta migración - sectores por empresa)
    - AuditoriaAcceso (se agrega en esta migración - para auditoría por empresa)
    
    MODELOS COMPARTIDOS (sin campo empresa - son globales):
    - Empresa (es el tenant mismo)
    - PerfilUsuario (tiene empresa pero es perfil de usuario global)
    - RolEmpresa (tiene empresa - roles por empresa)
    - RolDescripcion (extensión de Groups de Django - compartido)
    - PasswordChangeRequired (control de seguridad global)
    - User (modelo de Django - usuarios globales asignados a empresas vía PerfilUsuario)
    """

    dependencies = [
        ("App_LUMINOVA", "0034_alter_rolempresa_unique_together_rolempresa_nombre_and_more"),
    ]

    operations = [
        # =====================================================================
        # 1. USUARIODEPOSITO - Agregar campo empresa
        # =====================================================================
        migrations.AddField(
            model_name='usuariodeposito',
            name='empresa',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usuarios_depositos',
                to='App_LUMINOVA.empresa',
                help_text='Empresa a la que pertenece esta asignación'
            ),
        ),
        
        # Asignar empresa basándose en el depósito
        migrations.RunPython(assign_empresa_to_usuariodeposito, reverse_noop),
        
        # =====================================================================
        # 2. ESTADOORDEN - Agregar campo empresa (catálogo por empresa)
        # =====================================================================
        migrations.AddField(
            model_name='estadoorden',
            name='empresa',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='estados_orden',
                to='App_LUMINOVA.empresa',
                help_text='Empresa a la que pertenece este estado (null = compartido)'
            ),
        ),
        
        # Modificar unique para incluir empresa
        migrations.AlterField(
            model_name='estadoorden',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        
        migrations.AlterUniqueTogether(
            name='estadoorden',
            unique_together={('nombre', 'empresa')},
        ),
        
        migrations.RunPython(assign_empresa_to_estadoorden, reverse_noop),
        
        # =====================================================================
        # 3. SECTORASIGNADO - Agregar campo empresa (sectores por empresa)
        # =====================================================================
        migrations.AddField(
            model_name='sectorasignado',
            name='empresa',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sectores',
                to='App_LUMINOVA.empresa',
                help_text='Empresa a la que pertenece este sector (null = compartido)'
            ),
        ),
        
        migrations.AlterField(
            model_name='sectorasignado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        
        migrations.AlterUniqueTogether(
            name='sectorasignado',
            unique_together={('nombre', 'empresa')},
        ),
        
        migrations.RunPython(assign_empresa_to_sectorasignado, reverse_noop),
        
        # =====================================================================
        # 4. AUDITORIAACCESO - Agregar campo empresa (auditoría por empresa)
        # =====================================================================
        migrations.AddField(
            model_name='auditoriaacceso',
            name='empresa',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='auditorias',
                to='App_LUMINOVA.empresa',
                help_text='Empresa donde se realizó la acción auditada'
            ),
        ),
        
        migrations.RunPython(assign_empresa_to_auditoriaacceso, reverse_noop),
        
        # =====================================================================
        # 5. Agregar índices para optimizar consultas por empresa
        # =====================================================================
        migrations.AddIndex(
            model_name='usuariodeposito',
            index=models.Index(fields=['empresa'], name='idx_usuariodep_empresa'),
        ),
        
        migrations.AddIndex(
            model_name='estadoorden',
            index=models.Index(fields=['empresa'], name='idx_estadoorden_empresa'),
        ),
        
        migrations.AddIndex(
            model_name='sectorasignado',
            index=models.Index(fields=['empresa'], name='idx_sectorasignado_empresa'),
        ),
        
        migrations.AddIndex(
            model_name='auditoriaacceso',
            index=models.Index(fields=['empresa', 'fecha_hora'], name='idx_auditoria_empresa_fecha'),
        ),
    ]
