# Generated by Django 5.2.1 on 2026-01-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0035_complete_multitenancy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditoriaacceso",
            options={
                "ordering": ["-fecha_hora"],
                "verbose_name": "Auditoría de Acceso",
                "verbose_name_plural": "Auditorías de Acceso",
            },
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="estadoorden",
            options={
                "verbose_name": "Estado de Orden",
                "verbose_name_plural": "Estados de Orden",
            },
        ),
        migrations.AlterModelOptions(
            name="fabricante",
            options={
                "verbose_name": "Fabricante",
                "verbose_name_plural": "Fabricantes",
            },
        ),
        migrations.AlterModelOptions(
            name="factura",
            options={"verbose_name": "Factura", "verbose_name_plural": "Facturas"},
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={"verbose_name": "Proveedor", "verbose_name_plural": "Proveedores"},
        ),
        migrations.AlterModelOptions(
            name="sectorasignado",
            options={
                "verbose_name": "Sector Asignado",
                "verbose_name_plural": "Sectores Asignados",
            },
        ),
        migrations.RemoveIndex(
            model_name="estadoorden",
            name="idx_estadoorden_empresa",
        ),
        migrations.RemoveIndex(
            model_name="sectorasignado",
            name="idx_sectorasignado_empresa",
        ),
        migrations.RenameIndex(
            model_name="auditoriaacceso",
            new_name="App_LUMINOV_empresa_c18757_idx",
            old_name="idx_auditoria_empresa_fecha",
        ),
        migrations.RenameIndex(
            model_name="usuariodeposito",
            new_name="App_LUMINOV_empresa_111928_idx",
            old_name="idx_usuariodep_empresa",
        ),
        migrations.RemoveField(
            model_name="insumo",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="productoterminado",
            name="stock",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="fabricante",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="factura",
            name="numero_factura",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("email", "empresa"), ("nombre", "empresa")},
        ),
        migrations.AlterUniqueTogether(
            name="fabricante",
            unique_together={("nombre", "empresa")},
        ),
        migrations.AlterUniqueTogether(
            name="factura",
            unique_together={("numero_factura", "empresa")},
        ),
        migrations.AlterUniqueTogether(
            name="proveedor",
            unique_together={("nombre", "empresa")},
        ),
    ]
