# Generated by Django 5.2.1 on 2026-01-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "App_LUMINOVA",
            "0036_alter_auditoriaacceso_options_alter_cliente_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="total_orden_compra",
        ),
        migrations.RemoveField(
            model_name="ordenventa",
            name="total_ov",
        ),
    ]
