# Generated by Django 5.2.1 on 2026-01-14 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0037_remove_total_ov_and_total_orden_compra_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="fabricante",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Fabricante",
                "verbose_name_plural": "Fabricantes",
            },
        ),
        migrations.AlterModelOptions(
            name="insumo",
            options={
                "ordering": ["descripcion"],
                "verbose_name": "Insumo",
                "verbose_name_plural": "Insumos",
            },
        ),
        migrations.AlterModelOptions(
            name="itemordenventa",
            options={
                "verbose_name": "Item de Orden de Venta",
                "verbose_name_plural": "Items de Órdenes de Venta",
            },
        ),
        migrations.AlterModelOptions(
            name="loteproductoterminado",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Lote de Producto Terminado",
                "verbose_name_plural": "Lotes de Productos Terminados",
            },
        ),
        migrations.AlterModelOptions(
            name="movimientostock",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Movimiento de Stock",
                "verbose_name_plural": "Movimientos de Stock",
            },
        ),
        migrations.AlterModelOptions(
            name="orden",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
            },
        ),
        migrations.AlterModelOptions(
            name="ordenproduccion",
            options={
                "ordering": ["-fecha_solicitud"],
                "verbose_name": "Orden de Producción",
                "verbose_name_plural": "Órdenes de Producción",
            },
        ),
        migrations.AlterModelOptions(
            name="ordenventa",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Orden de Venta",
                "verbose_name_plural": "Órdenes de Venta",
            },
        ),
        migrations.AlterModelOptions(
            name="productoterminado",
            options={
                "ordering": ["descripcion"],
                "verbose_name": "Producto Terminado",
                "verbose_name_plural": "Productos Terminados",
            },
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.AlterModelOptions(
            name="reportes",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Reporte de Incidencia",
                "verbose_name_plural": "Reportes de Incidencias",
            },
        ),
        migrations.AlterModelOptions(
            name="stockinsumo",
            options={
                "verbose_name": "Stock de Insumo",
                "verbose_name_plural": "Stocks de Insumos",
            },
        ),
        migrations.AlterModelOptions(
            name="stockproductoterminado",
            options={
                "verbose_name": "Stock de Producto Terminado",
                "verbose_name_plural": "Stocks de Productos Terminados",
            },
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["empresa", "nombre"], name="App_LUMINOV_empresa_d58325_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="componenteproducto",
            index=models.Index(
                fields=["producto_terminado"], name="App_LUMINOV_product_e266b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="componenteproducto",
            index=models.Index(
                fields=["empresa"], name="App_LUMINOV_empresa_ca57e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fabricante",
            index=models.Index(
                fields=["empresa", "nombre"], name="App_LUMINOV_empresa_1a1690_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historialov",
            index=models.Index(
                fields=["orden_venta", "fecha_evento"],
                name="App_LUMINOV_orden_v_36d7ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialov",
            index=models.Index(
                fields=["empresa"], name="App_LUMINOV_empresa_91cc72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insumo",
            index=models.Index(
                fields=["empresa", "deposito"], name="App_LUMINOV_empresa_7765a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insumo",
            index=models.Index(
                fields=["empresa", "categoria"], name="App_LUMINOV_empresa_0f97f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insumo",
            index=models.Index(
                fields=["deposito", "categoria"], name="App_LUMINOV_deposit_3751e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemordenventa",
            index=models.Index(
                fields=["orden_venta"], name="App_LUMINOV_orden_v_84be3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemordenventa",
            index=models.Index(
                fields=["empresa"], name="App_LUMINOV_empresa_d24537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loteproductoterminado",
            index=models.Index(
                fields=["empresa", "op_asociada"], name="App_LUMINOV_empresa_b5ee23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loteproductoterminado",
            index=models.Index(
                fields=["empresa", "producto"], name="App_LUMINOV_empresa_2b3ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loteproductoterminado",
            index=models.Index(
                fields=["enviado"], name="App_LUMINOV_enviado_d7e654_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientostock",
            index=models.Index(
                fields=["empresa", "fecha"], name="App_LUMINOV_empresa_56604f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientostock",
            index=models.Index(
                fields=["empresa", "tipo"], name="App_LUMINOV_empresa_1147f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientostock",
            index=models.Index(
                fields=["deposito_origen", "fecha"],
                name="App_LUMINOV_deposit_a62071_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movimientostock",
            index=models.Index(
                fields=["deposito_destino", "fecha"],
                name="App_LUMINOV_deposit_fff030_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ofertaproveedor",
            index=models.Index(
                fields=["empresa"], name="App_LUMINOV_empresa_5d4920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ofertaproveedor",
            index=models.Index(
                fields=["insumo"], name="App_LUMINOV_insumo__1d0f1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ofertaproveedor",
            index=models.Index(
                fields=["proveedor"], name="App_LUMINOV_proveed_d6eff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(
                fields=["empresa", "estado"], name="App_LUMINOV_empresa_714c66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(
                fields=["empresa", "deposito"], name="App_LUMINOV_empresa_fc19da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(
                fields=["estado", "fecha_creacion"],
                name="App_LUMINOV_estado_5aad37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(
                fields=["proveedor", "estado"], name="App_LUMINOV_proveed_6a8f50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordenproduccion",
            index=models.Index(
                fields=["empresa", "estado_op"], name="App_LUMINOV_empresa_bffaa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordenproduccion",
            index=models.Index(
                fields=["producto_a_producir", "estado_op"],
                name="App_LUMINOV_product_220495_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordenproduccion",
            index=models.Index(
                fields=["orden_venta_origen"], name="App_LUMINOV_orden_v_30922a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordenproduccion",
            index=models.Index(
                fields=["empresa", "fecha_solicitud"],
                name="App_LUMINOV_empresa_ed1d1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordenventa",
            index=models.Index(
                fields=["empresa", "estado"], name="App_LUMINOV_empresa_6a7af8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordenventa",
            index=models.Index(
                fields=["empresa", "fecha_creacion"],
                name="App_LUMINOV_empresa_a5365e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordenventa",
            index=models.Index(
                fields=["estado", "fecha_creacion"],
                name="App_LUMINOV_estado_64db5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productoterminado",
            index=models.Index(
                fields=["empresa", "deposito"], name="App_LUMINOV_empresa_32fb14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productoterminado",
            index=models.Index(
                fields=["empresa", "categoria"], name="App_LUMINOV_empresa_5b2fce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productoterminado",
            index=models.Index(
                fields=["deposito", "categoria"], name="App_LUMINOV_deposit_f6aa91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proveedor",
            index=models.Index(
                fields=["empresa", "nombre"], name="App_LUMINOV_empresa_c2beee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportes",
            index=models.Index(
                fields=["empresa", "resuelto"], name="App_LUMINOV_empresa_4b41c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportes",
            index=models.Index(
                fields=["empresa", "fecha"], name="App_LUMINOV_empresa_1a528f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportes",
            index=models.Index(
                fields=["orden_produccion_asociada"],
                name="App_LUMINOV_orden_p_9549a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockinsumo",
            index=models.Index(
                fields=["empresa"], name="App_LUMINOV_empresa_151737_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockinsumo",
            index=models.Index(
                fields=["insumo"], name="App_LUMINOV_insumo__518aaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockproductoterminado",
            index=models.Index(
                fields=["empresa"], name="App_LUMINOV_empresa_602efa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockproductoterminado",
            index=models.Index(
                fields=["producto"], name="App_LUMINOV_product_fabe55_idx"
            ),
        ),
    ]
