# Generated by Django 5.2.1 on 2026-01-14 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0038_add_performance_indexes_and_ordering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialImportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_importacion",
                    models.CharField(
                        choices=[
                            ("insumos", "Insumos"),
                            ("productos", "Productos Terminados"),
                            ("clientes", "Clientes"),
                            ("proveedores", "Proveedores"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Importación",
                    ),
                ),
                (
                    "nombre_archivo",
                    models.CharField(max_length=255, verbose_name="Nombre del Archivo"),
                ),
                (
                    "fecha_importacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Importación",
                    ),
                ),
                (
                    "registros_importados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros Importados"
                    ),
                ),
                (
                    "registros_actualizados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros Actualizados"
                    ),
                ),
                (
                    "registros_con_error",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros con Error"
                    ),
                ),
                (
                    "exitoso",
                    models.BooleanField(
                        default=False, verbose_name="Importación Exitosa"
                    ),
                ),
                (
                    "errores_detalle",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de errores encontrados durante la importación",
                        verbose_name="Detalle de Errores",
                    ),
                ),
                (
                    "warnings_detalle",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Detalle de Advertencias"
                    ),
                ),
                (
                    "deposito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importaciones",
                        to="App_LUMINOVA.deposito",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="App_LUMINOVA.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Importación",
                "verbose_name_plural": "Historial de Importaciones",
                "ordering": ["-fecha_importacion"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "fecha_importacion"],
                        name="App_LUMINOV_empresa_99ef31_idx",
                    ),
                    models.Index(
                        fields=["tipo_importacion"],
                        name="App_LUMINOV_tipo_im_68064d_idx",
                    ),
                    models.Index(
                        fields=["usuario"], name="App_LUMINOV_usuario_8ccac3_idx"
                    ),
                ],
            },
        ),
    ]
