# Generated by Django 5.2.1 on 2026-01-14 20:43

import re
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


def generate_schema_names(apps, schema_editor):
    """
    Genera schema_name para empresas existentes.
    - La empresa con ID=1 (Luminova ERP) será el tenant público -> 'public'
    - Las demás empresas tendrán schema basado en su nombre normalizado
    """
    Empresa = apps.get_model('App_LUMINOVA', 'Empresa')
    for empresa in Empresa.objects.all():
        if empresa.id == 1:
            # La primera empresa es el tenant público
            empresa.schema_name = 'public'
        else:
            # Normalizar nombre: minúsculas, sin espacios, solo alfanuméricos
            schema = re.sub(r'[^a-z0-9]', '_', empresa.nombre.lower())
            schema = re.sub(r'_+', '_', schema)  # Múltiples _ a uno solo
            schema = schema.strip('_')[:63]  # Máximo 63 caracteres
            empresa.schema_name = schema
        empresa.save()


def create_initial_domains(apps, schema_editor):
    """
    Crea dominios iniciales para las empresas existentes.
    """
    Empresa = apps.get_model('App_LUMINOVA', 'Empresa')
    Domain = apps.get_model('App_LUMINOVA', 'Domain')
    
    for empresa in Empresa.objects.all():
        if empresa.schema_name == 'public':
            # Tenant público accesible desde localhost
            Domain.objects.create(
                domain='localhost',
                tenant=empresa,
                is_primary=True
            )
        else:
            # Otros tenants con subdominio
            Domain.objects.create(
                domain=f'{empresa.schema_name}.localhost',
                tenant=empresa,
                is_primary=True
            )


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0039_add_historial_importacion"),
    ]

    operations = [
        # 1. Agregar campo schema_name con default temporal
        migrations.AddField(
            model_name="empresa",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                default='temp_schema',
                max_length=63,
                unique=False,  # Temporalmente sin unique para la migración
            ),
            preserve_default=False,
        ),
        
        # 2. Generar schema_names correctos
        migrations.RunPython(generate_schema_names, migrations.RunPython.noop),
        
        # 3. Ahora sí, hacer el campo unique y agregar validator
        migrations.AlterField(
            model_name="empresa",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                max_length=63,
                unique=True,
                validators=[django_tenants.postgresql_backend.base._check_schema_name],
            ),
        ),
        
        # 4. Crear modelo Domain
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="App_LUMINOVA.empresa",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        
        # 5. Crear dominios iniciales
        migrations.RunPython(create_initial_domains, migrations.RunPython.noop),
    ]
