# Generated by Django 5.2.1 on 2025-07-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaProductoTerminado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre Categoría PT"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="categorias_productos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Producto Terminado",
                "verbose_name_plural": "Categorías de Productos Terminados",
            },
        ),
        migrations.CreateModel(
            name="ProductoTerminado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("modelo", models.CharField(blank=True, max_length=50, null=True)),
                ("potencia", models.IntegerField(blank=True, null=True)),
                ("acabado", models.CharField(blank=True, max_length=50, null=True)),
                ("color_luz", models.CharField(blank=True, max_length=50, null=True)),
                ("material", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos_terminados/"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos_terminados",
                        to="productos.categoriaproductoterminado",
                    ),
                ),
            ],
        ),
    ]
