# Generated by Django 5.2.1 on 2025-07-27 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_LUMINOVA", "0003_remove_ordenproduccion_estado_op_and_more"),
        ("insumos", "0003_orden"),
        ("productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SectorAsignado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_op",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="N° Orden de Producción",
                    ),
                ),
                ("cantidad_a_producir", models.PositiveIntegerField()),
                (
                    "fecha_solicitud",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_inicio_real", models.DateTimeField(blank=True, null=True)),
                ("fecha_inicio_planificada", models.DateField(blank=True, null=True)),
                ("fecha_fin_real", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin_planificada", models.DateField(blank=True, null=True)),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "estado_op",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_estado",
                        to="productos.estadoorden",
                    ),
                ),
                (
                    "orden_venta_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_generadas",
                        to="App_LUMINOVA.ordenventa",
                    ),
                ),
                (
                    "producto_a_producir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_produccion",
                        to="productos.productoterminado",
                    ),
                ),
                (
                    "sector_asignado_op",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ops_sector",
                        to="productos.sectorasignado",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="loteproductoterminado",
            name="op_asociada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_pt",
                to="productos.ordenproduccion",
            ),
        ),
        migrations.CreateModel(
            name="Reportes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_reporte", models.CharField(max_length=20, unique=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("tipo_problema", models.CharField(max_length=100)),
                ("informe_reporte", models.TextField(blank=True, null=True)),
                (
                    "resuelto",
                    models.BooleanField(
                        default=False, verbose_name="¿Problema Resuelto?"
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Resolución"
                    ),
                ),
                (
                    "orden_produccion_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_incidencia",
                        to="productos.ordenproduccion",
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector_reporta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_originados_aqui",
                        to="productos.sectorasignado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponenteProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_necesaria", models.PositiveIntegerField(default=1)),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="insumos.insumo"
                    ),
                ),
                (
                    "producto_terminado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes_requeridos",
                        to="productos.productoterminado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente de Producto (BOM)",
                "verbose_name_plural": "Componentes de Productos (BOM)",
                "unique_together": {("producto_terminado", "insumo")},
            },
        ),
    ]
