from django.urls import path
from ..views import (
    deposito_view,
    deposito_solicitudes_insumos_view,
    deposito_detalle_solicitud_op_view,
    deposito_enviar_insumos_op_view,
    deposito_enviar_lote_pt_view,
    recepcion_pedidos_view,
    recibir_pedido_oc_view,
    ProveedorListView,
    ProveedorDetailView,
    proveedor_create_view, # Vista para crear un nuevo proveedor - Refactorizar a ProveedorCreateView usando CBV
    ProveedorUpdateView,
    ProveedorDeleteView,
    FabricanteDetailView,
    FabricanteCreateView,
    FabricanteUpdateView,
    FabricanteDeleteView,
    Categoria_IDetailView,
    Categoria_ICreateView,
    Categoria_IUpdateView,
    Categoria_IDeleteView,
    Categoria_PTDetailView,
    Categoria_PTCreateView,
    Categoria_PTUpdateView,
    Categoria_PTDeleteView,
    InsumoCreateView,
    InsumoUpdateView,
    InsumoDeleteView,
    ProductoTerminadoCreateView,
    ProductoTerminadoUpdateView,
    ProductoTerminadoDeleteView,
)

# Rutas de Ventas
urlpatterns = [
    path("deposito/", deposito_view, name="deposito_view"),
    path(
        "deposito/solicitudes-insumos/",
        deposito_solicitudes_insumos_view,
        name="deposito_solicitudes_insumos",
    ),
    path(
        "deposito/solicitud-op/<int:op_id>/",
        deposito_detalle_solicitud_op_view,
        name="deposito_detalle_solicitud_op",
    ),
    path(
        "deposito/enviar-insumos-op/<int:op_id>/",
        deposito_enviar_insumos_op_view,
        name="deposito_enviar_insumos_op",
    ),
    path(
        "deposito/enviar-lote-pt/<int:lote_id>/",
        deposito_enviar_lote_pt_view,
        name="deposito_enviar_lote_pt",
    ),
    path(
        "deposito/recepcion-pedidos/",
        recepcion_pedidos_view,
        name="deposito_recepcion_pedidos",
    ),
    path(
        "deposito/recibir-pedido/<int:oc_id>/",
        recibir_pedido_oc_view,
        name="deposito_recibir_pedido",
    ),
    # CRUDs para Fabricantes, Proveedores (Class-Based Views)
    path(
        "ventas/proveedores/proveedor/",
        ProveedorListView.as_view(),
        name="proveedor_list",
    ),
    path(
        "ventas/proveedores/proveedor/<int:pk>/",
        ProveedorDetailView.as_view(),
        name="proveedor_detail",
    ),
    path(
        "ventas/proveedores/proveedor/crear/",
        proveedor_create_view,
        name="proveedor_create",
    ),
    path(
        "ventas/proveedores/proveedor/editar/<int:pk>/",
        ProveedorUpdateView.as_view(),
        name="proveedor_edit",
    ),
    path(
        "ventas/proveedores/proveedor/eliminar/<int:pk>/",
        ProveedorDeleteView.as_view(),
        name="proveedor_delete",
    ),
    path(
        "ventas/fabricantes/<int:pk>/",
        FabricanteDetailView.as_view(),
        name="fabricante_detail",
    ),
    path(
        "ventas/fabricantes/crear/",
        FabricanteCreateView.as_view(),
        name="fabricante_create",
    ),
    path(
        "ventas/fabricantes/editar/<int:pk>/",
        FabricanteUpdateView.as_view(),
        name="fabricante_edit",
    ),
    path(
        "ventas/fabricantes/eliminar/<int:pk>/",
        FabricanteDeleteView.as_view(),
        name="fabricante_delete",
    ),
    # CRUDs para Categorías, Insumos, Productos Terminados (Class-Based Views)
    path(
        "deposito/categorias-insumo/<int:pk>/",
        Categoria_IDetailView.as_view(),
        name="categoria_i_detail",
    ),
    path(
        "deposito/categorias-insumo/crear/",
        Categoria_ICreateView.as_view(),
        name="categoria_i_create",
    ),
    path(
        "deposito/categorias-insumo/editar/<int:pk>/",
        Categoria_IUpdateView.as_view(),
        name="categoria_i_edit",
    ),
    path(
        "deposito/categorias-insumo/eliminar/<int:pk>/",
        Categoria_IDeleteView.as_view(),
        name="categoria_i_delete",
    ),
    path(
        "deposito/categorias-producto-terminado/<int:pk>/",
        Categoria_PTDetailView.as_view(),
        name="categoria_pt_detail",
    ),
    path(
        "deposito/categorias-producto-terminado/crear/",
        Categoria_PTCreateView.as_view(),
        name="categoria_pt_create",
    ),
    path(
        "deposito/categorias-producto-terminado/editar/<int:pk>/",
        Categoria_PTUpdateView.as_view(),
        name="categoria_pt_edit",
    ),
    path(
        "deposito/categorias-producto-terminado/eliminar/<int:pk>/",
        Categoria_PTDeleteView.as_view(),
        name="categoria_pt_delete",
    ),
    path("deposito/insumos/crear/", InsumoCreateView.as_view(), name="insumo_create"),
    path(
        "deposito/insumos/editar/<int:pk>/",
        InsumoUpdateView.as_view(),
        name="insumo_edit",
    ),
    path(
        "deposito/insumos/eliminar/<int:pk>/",
        InsumoDeleteView.as_view(),
        name="insumo_delete",
    ),
    # path('deposito/insumos/', InsumosListView.as_view(), name='insumos_list'), # Descomentar si necesitas una lista general de todos los insumos
    path(
        "deposito/productos-terminados/crear/",
        ProductoTerminadoCreateView.as_view(),
        name="producto_terminado_create",
    ),
    path(
        "deposito/productos-terminados/editar/<int:pk>/",
        ProductoTerminadoUpdateView.as_view(),
        name="producto_terminado_edit",
    ),
    path(
        "deposito/productos-terminados/eliminar/<int:pk>/",
        ProductoTerminadoDeleteView.as_view(),
        name="producto_terminado_delete",
    ),
]