name: Create branch for issue

on:
  issues:
    types:
      - assigned

permissions:
  contents: write
  issues: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          BRANCH_NAME="issue-${ISSUE_NUMBER}"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hola @${{ github.event.assignee.login }},
            Se te ha asignado el issue **${{ github.event.issue.title }}**.
            Se ha creado la rama **issue-${{ github.event.issue.number }}** para que puedas trabajar en ella.
          token: ${{ secrets.GITHUB_TOKEN }}
